### ISSUE TITLE
WiFi connects correctly but Runtime Error nontheless

### ISSUE THREAD

**Issue by TheConfax** [changyuheng/pywinwifi#12]
`Traceback (most recent call last):
  File "c:\users\theco\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\theco\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\theco\AppData\Local\Programs\Python\Python39\Scripts\wifi.exe\__main__.py", line 7, in <module>
  File "c:\users\theco\appdata\local\programs\python\python39\lib\site-packages\winwifi\__main__.py", line 95, in main
    return Wifi.run()[1]
  File "c:\users\theco\appdata\local\programs\python\python39\lib\site-packages\plumbum\cli\application.py", line 577, in run
    inst, retcode = subapp.run(argv, exit=False)
  File "c:\users\theco\appdata\local\programs\python\python39\lib\site-packages\plumbum\cli\application.py", line 572, in run
    retcode = inst.main(*tailargs)
  File "c:\users\theco\appdata\local\programs\python\python39\lib\site-packages\winwifi\__main__.py", line 36, in main
    WinWiFi.connect(ssid=ssid, passwd=passwd, remember=not self._one_shot)
  File "c:\users\theco\appdata\local\programs\python\python39\lib\site-packages\winwifi\main.py", line 207, in connect
    raise RuntimeError('Cannot connect to Wi-Fi AP')
RuntimeError: Cannot connect to Wi-Fi AP`

**Comment by TheConfax** [comment]
Is this project still supported?

**Comment by GetThatGuyOverThereIn10293** [comment]
you are 𝕥𝕙𝕖 𝕘𝕒𝕪𝕖𝕤𝕥 𝕗𝕜𝕟 𝕟𝕘𝕒, so go ցҽէ ą Ӏìƒҽ! you ｃ𝐮几т!
